sonar.projectKey=base-nestjs
sonar.projectName=Base NestJS Project
sonar.projectVersion=1.0
sonar.sources=src
sonar.tests=test
sonar.exclusions=**/*.spec.ts,**/*.test.ts,**/*.e2e-spec.ts,**/test/**/*,**/node_modules/**, **/dist/**
sonar.typescript.tsconfigPath=tsconfig.json
sonar.sourceEncoding=UTF-8
sonar.testEncoding=UTF-8 
sonar.language=ts
sonar.typescript.lcov.reportPaths=coverage/lcov.info
sonar.host.url=http://localhost:9000
sonar.login=admin
sonar.password=admin